# Generated by Django 4.2.3 on 2023-11-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_depth_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.IntegerField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nomenclature',
            field=models.IntegerField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
