# Generated by Django 4.2.3 on 2023-12-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_name_product_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nomenclature',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
