# Generated by Django 4.2.3 on 2023-12-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_article_alter_product_nomenclature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_class',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_class',
        ),
        migrations.DeleteModel(
            name='ProductClass',
        ),
    ]
