# Generated by Django 4.2.3 on 2023-12-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_subcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nomenclature',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', unique=True),
            preserve_default=False,
        ),
    ]
