# Generated by Django 4.2.3 on 2023-12-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_nomenclature_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='type',
        ),
    ]
